name: Auto Job Reset

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # This cron expression means "every 30 minutes"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install

    - name: Start application
      run: |
        nohup npm start &
        echo $! > /tmp/app.pid # Save the process ID to a file

    - name: Sleep and Stop Application
      run: |
        sleep 5m
        kill $(cat /tmp/app.pid) # Kill the process using the saved PID
