name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: npm start

    - name: Wait for 3 minutes
      run: sleep 180

    - name: Trigger next workflow
      uses: actions/github-script@v6
      with:
        script: |
          const octokit = require('@actions/github').getOctokit(process.env.GITHUB_TOKEN);
          const repo = process.env.GITHUB_REPOSITORY;
          await octokit.rest.actions.createWorkflowDispatch({
            owner: repo.split('/')[0],
            repo: repo.split('/')[1],
            workflow: 'trigger.yml',
            ref: 'main'
          });
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
